// <auto-generated />
using System;
using EasyBeady.Database.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyBeady.Api.Database.Domain.Migrations
{
    [DbContext(typeof(SchemasDbContext))]
    [Migration("20250615150317_AddPreviewAndLinesCompletedToArray")]
    partial class AddPreviewAndLinesCompletedToArray
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EasyBeady.Database.Entities.Domain.SchemaModel", b =>
                {
                    b.Property<Guid>("SchemaId")
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<short>("Height")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime");

                    b.Property<byte[]>("LinesCompleted")
                        .IsRequired()
                        .HasColumnType("tinyblob");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("Schema")
                        .IsRequired()
                        .HasColumnType("mediumblob");

                    b.Property<string>("SchemaPreview")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("UserId")
                        .IsRequired()
                        .HasColumnType("binary(16)");

                    b.Property<short>("Width")
                        .HasColumnType("smallint");

                    b.HasKey("SchemaId");

                    b.ToTable("Schemas");
                });
#pragma warning restore 612, 618
        }
    }
}
